# https://taskfile.dev

version: '2'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  install-pq:
    desc: _
    cmds:
      - conda install -y -c conda-forge pyarrow

