# https://taskfile.dev

version: '2'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  prep-wss-pers:
    cmds:
    - python app.py start-index ~/wss/pers