# Use root/example as user/password credentials
# see=https://jenkins.io/solutions/pipeline/
version: '3.1'

services:
  jen_master:
      image: 'jenkins/jenkins:lts'
      # restart: always
      environment:
        - JAVA_OPTS=-Dhudson.footerURL=http://cicd-jen.jen_master
      volumes:
        - jenkins_home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - "8888:8080"
        - "50000:50000"
volumes:
  jenkins_home: