# https://taskfile.dev

version: '2.3'

includes:
  testcli: tests

vars:
  GREETING: dictdir

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -l
    silent: true

  test:
    desc: _
    cmds:
      - pytest

  test-all:
    desc: _
    deps:
      - testcli:all
      - test-cov

  test-cov:
    desc: Run Coverage Tests
    cmds:
      # prepare output dirs
      - mkdir -p coverage_html_report
      - mkdir -p build_info
      - rm -rf build_info/report_total.txt

      # run pytest with coverage [multi: -n 4]
      - |
        python -m pytest \
        --cov-config .covrc \
        --cov-report html \
        --cov-report term \
        --cov . \
        --junit-xml=coverage_html_report/pytest_unit.junit.xml \
        . -s 2>&1 | tee cov.log || echo some fails

      # preprare report
      - |
        python -c 'print(open("cov.log").read().split("-- coverage:")[1].split("TOTAL")[0])' \
          > build_info/coverage_txt_report.txt
        cat cov.log | grep passed | tr -d '=,' > build_info/tests_passed_report.txt \
        && cat cov.log | grep TOTAL | awk '{print $6,  "of", $2, "lines"}' > build_info/coverage_total.txt \
        && echo rm cov.log

      # total report
      - cat build_info/*_report.txt >> build_info/report_total.txt

  clean:
    desc: _
    cmds:
      - rm -rf out build dist build_info coverage_html_report .pytest_cache

  fix:
    desc: run code autoformat
    cmds:
      - yapf -ir -e .venv .

# --- Build in clean venv ---

  build:
    desc:
    cmds:
      - .venv/bin/python ppyinst.py dictfold.py -F

  clean-venv:
    desc: _
    cmds:
     - rm -rf .venv

  create-venv:
    desc: _
    cmds:
     - python -m venv .venv
     - .venv/bin/python -m pip install -r requirements.txt
     - .venv/bin/python -m pip install pyinstaller

  rrbuild:
    desc: "Build in clear venv so pyinstaller wont create big exe"
    deps:
      - clean-venv
      - clean
    cmds:
      - task: create-venv
      - task: build

# -- package tasks
  pack-clean:
    desc: clean package files
    cmds:
      - rm -rf dist
      - rm -rf refstore.egg-info

  pack-build:
    desc: build package for publish
    deps: [pack-clean]
    cmds:
      - .venv/bin/python setup.py sdist --formats=gztar,zip