name: Python application Special
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./dictdir
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
      working-directory: ${{ env.working-directory }}
    - name: Test with pytest
      run: |
        python -m pip install -r requirements-dev.txt
        pytest dictdir
      working-directory: ${{ env.working-directory }}

    - name: Create Exe
#        mv ../dist ../dist_exe
      run: |
        python -m pip install pyinstaller
        python ../ppyinst.py dictfold.py -F
        ls -alh dist
      working-directory: ${{ env.working-directory }}/dictdir

    - name: Create Package
      run: |
        python setup.py sdist --formats=gztar,zip
        ls -alh dist
      working-directory: ${{ env.working-directory }}

